---
# this playbook deploye the whole application stack in this site


#update kernel and OS on Centos 9
- name: Update Kernel And OS
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - patching


# Install the common packages on all servers
- name: Install  the common packages
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - common

#configure the common security on all the servers
- name: Install  the common packages
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - security




#configure web proxy 
- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ansible
  become: yes

  roles:
    - web

    # this playboook will configure the hpa proxy

- name: configure and deploy the Haproxy
  hosts: haproxy
  remote_user: ansible
  become: yes

  roles:
    - hpa

