---
- name: Install HAProxy
  yum:
    name: "{{ haproxy_package }}"
    state: present
  notify: Restart HAProxy

- name: Ensure HAProxy configuration directory exists
  file:
    path: "{{ haproxy_cfg_dir }}"
    state: directory
    owner: root
    group: root

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy

- name: Ensure HAProxy is started and enabled
  service:
    name: "{{ haproxy_service }}"
    state: started
    enabled: yes
